renv::restore()
here::i_am("load_packages.R")
library("here")
library("clustermq")
library("tidyverse")
library("assertthat")
library("lubridate")
library("bayesplot")
library("egg")
library("qs")
library("RColorBrewer")
library("OncoBayes2")
library("posterior")
library("brms")
library("survival")
library("knitr")
library("tidyr")
library("quarto")

options(brms.file_refit="on_change")
options(brms.backend="cmdstanr")
options(cmdstanr_write_stan_file_dir=here("cache"))

print("Packages & Options loaded")